### ISSUE TITLE
XpoDatabase for connecting to multiple databases

### ISSUE THREAD

**Issue by cuongpv88** [donwibier/DXWeb#11]
XpoDatabase for connecting to multiple databases

Hello team,

I just wanted to ask you, is it possible to bind multiple databases with the XpoDatabase framework?

I made it like this
 //Initialize XPODataLayer / Database	
            services.AddXpoDatabases(
                new Action<XpoDatabaseOptions>[]
                {
                    new Action<XpoDatabaseOptions>((o) => {
                        o.Name="ERP";
                        o.ConnectionString=Configuration.GetConnectionString("ERP");
                        o.EnableCaching = false;
                        o.UpdateSchema = AutoCreateOption.None;
                    }),
                    new Action<XpoDatabaseOptions>((o) => {
                        o.Name="EasyGA";
                        o.ConnectionString=Configuration.GetConnectionString("EasyGA");
                        o.EnableCaching = false;
                        o.UpdateSchema = AutoCreateOption.None;
                    }),
                    new Action<XpoDatabaseOptions>((o) => {
                        o.Name="DefaultConnection";
                        o.ConnectionString=Configuration.GetConnectionString("DefaultConnection");
                        o.EnableCaching = true;
                        o.UpdateSchema = AutoCreateOption.None;
                    })

                });

![image](https://user-images.githubusercontent.com/2852089/120881045-8a6ea380-c5f8-11eb-895d-e313bfc20cf5.png)

**Comment by donwibier** [comment]
Hi there is some (experimental) support for this:
You will need to decorate your persistent classes with the XpoDataLayer attribute.
It takes a DataLayer name property which should match the connectionName in your config file.
The XpoDatabase class has overloaded methods which will have an extra parameter which is the dataLayer name.
Hope this helps
