### ISSUE TITLE
Still cant create custom Fields (6 Months Later)

### ISSUE THREAD

**Issue by IncreaseComputers** [donwibier/DXWeb#12]
I still cant get custom properties to work on the user model, would it be possible to add a simple example of adding custom fields - just a simple example covering the files we need to modify and what we need to put in them?

**Comment by donwibier** [comment]
In case you haven't found it, please take a look at the DX.Test.Web.Blazor example:
/Data/Identity.cs has a custom ApplicationUser, XpoApplicationUser and ApplicationMapper class

This example also has Full Blazor Server Authentication with Blazor Pages instead of Razor Pages.
