### ISSUE TITLE
Latest DX.Data.Xpo.Identity Version assign extra properties

### ISSUE THREAD

**Issue by petsasj** [donwibier/DXWeb#3]
Hello,

Before refactoring your project, I was able to assign extra properties to both the ApplicationUser and the XPOApplication user, and assign that property via the 

`public override void Assign(object source, int loadingFlags)`

method.

It is no longer available. How is it possible to add extra properties to the ApplicationUser/XpoApplicationUser?

Thanks

**Comment by IncreaseComputers** [comment]
+1 Im also having this issue - can we have an example please?

**Comment by donwibier** [comment]
Hi,

I have introduced the concept of a mapper class and a validator class.
The mapper class handles the copying of properties from and to the DTO classes.
An example can be found here: https://github.com/donwibier/DXWeb/blob/master/README.md

If you have extra properties, derive your own mapper class from the User mapper and register it in your Startup.cs file.
I have also updated the examples in the repo with this.

**Comment by paolobeda** [comment]
Hi Don,
first of all thank you for your great job.
You wrote that you updated the examples in the repo. I can't find an example with an extra property.
Where can I find it?
My issue is that the ApplicationUser's extra property is saved in the DB but it's value never get back in the ApplicationUser's instance and I don't understand why.

**Comment by IncreaseComputers** [comment]
I have raised a new ticket as I am also still having issues getting this to work.
