### ISSUE TITLE
Deleting roles with users

### ISSUE THREAD

**Issue by mkalinski93** [donwibier/DXWeb#6]
Hey,

it seems to be that you have to clear all users from a role, that you can delete it then.

`public async Task<IdentityResult> DeleteRoleAsync(string roleName) {
          if(await this.GetApplicationRole(roleName) is ApplicationRole role) {
              return await this.RoleManager.DeleteAsync(role);
          }
          return ErrorConstants.RoleNotFound;
      }`

If the role has users assigned, the IdentityResult will still be succeeded, but the role still persists in the database.

**Comment by donwibier** [comment]
Hi,
I've just pushed a new version to NuGet which should take care of this issue.
It's v20.1.7.12

**Comment by mkalinski93** [comment]
hey,

unfortunately, that did not work. I´ve noticed that the XPRoleStoreValidator validates against this condition.

`            if (role != null) {
                int userCount = (int)role.Session.Evaluate(typeof(XpoDxUser),
                    CriteriaOperator.Parse("Count"),
                    CriteriaOperator.Parse("Roles[Id == ?]", role.ID));
                if (userCount > 0)
                    result = new DataValidationResult<TKey> {
                        ResultType = DataValidationResultType.Error,
                        ID = role.ID,
                        Message = String.Format("Role '{0}' cannot be deleted because there are users in this Role", role.Name)
                    };
            }`

The role object will be deleted (and within its users) when the validation is successful (which will never succeed)
I´ve forked this repo and modified it on my end.
